### ISSUE TITLE
Tech2 .bin file

### ISSUE THREAD

**Issue by dkatsariotis** [tech2wiki/tech2wiki-website#23]
Opel / Vauxhall v184.000 Greek bin not working on Tech2

https://github.com/tech2wiki/tech2wiki-website/raw/main/assets/binfiles/tech2_card_opel_v184.000_gr.zip

**Comment by berrydejager** [comment]
What does "not working" mean in detail? 

If the file doesn't work at all; please create a PR to have the file removed or replaced by working copy. 

Please read the contribute section on the wiki.

**Comment by dkatsariotis** [comment]
.bin is being writen using Tech2 Card Writer and then Tech2 does not boot the image.
English version runs just fine.

Unfortunately I do not have access to a working version of v184.000 Greek in order to make a new bin and commit it.

**Comment by berrydejager** [comment]
Fair enough, just create a pull request to retract the non working Greek file.

**Comment by dkatsariotis** [comment]
New file added for v184 and many others
